# BackPacks by Michael1011
# Version: 1.2.8

OnlyPlayers: "&4Only players &ccan execute this command!"
# When the console wants to execute a command wich is only for players.

NoPermission: "&4You do not have enought permissions!"
# If a player has not enough permission he will get this message

Reload: "&eReloaded config files &6successfully&e!"
# When you reload the config files

Usage: "&4&lUsage:"
# Before every help page

BPHelp:
  1: "&6/bp: &eshows this page"
  2: "&6/bpreload: &eto reload the config files"
  3: "&6/bpgive: &eto give anyone a backpack"
  4: "&6/bpopen: &eto open the backpack of someone"
# The help of /bp

BPGiveHelp:
  1: "&6/bpgive <item>: &eto give you the backpack <item>"
  2: "&6/bpgive <item> <player>: &eto give <player> the backpkack <item>"
  3: "&6Available Items are: &elittlebp ; normalbp ; enderbp ; workbenchbp ; enchantingbp ; furnacebp"
# Help of /bp give

GaveBackPack: "&eAdded the &6backpack %backpack% &eto your inventory!"
# When you give yourself an backpack. %backpack% is the backpack.

GaveBackPackOthers: "&eAdded the &6backpack %backpack% &eto the inventory of &6%target%!"
# When you give any player a backpack. %backpack% is the backpack und %target% the player.

GiveNotFound: "&cThe backpack &4%backpack% couldn't &cbe found!"
# When you want to give anyone a backpack that doosn't exists. %backpack% is the wrong backpack.

GivePlayerNotFound: "&cThe player &4%target% couldn't &cbe found!"
# When you want to give a backpack to a player but the player isn't online. %target% is the player.

OpenHelp: "&6/bpopen <backpack> <player>: &eto open backpack <backpack> (little, normal) of player <player>"

MySQL:
  enable: false
# When its false the plugin will use a config file. Before you enable this setup the MySQL host below!

  host: "localhost"
# IP adress or domain of you MySQL host.
  port: "3306"
# Port of your MySQL Server.
  database: "database"
# Wich database do you want to use?
  username: "root"
# The user must have all permission on the database above!
  password: "password"
# The password of the player above.
