main: main.Main
name: BackPacks-1.9
version: 1.2.8
description: This is a simple plugin for BackPacks
author: Michael1011

commands:
  bp:
    usage: /bp
    description: "Main command"
  bpgive:
    usage: /bpgive <arg>
    description: "to give a player a backpack"
  bpopen:
    usage: /bpopen <backpack> <player> (Works only if you are using a MySQL database!)
    description: "Open the backpack of a player. Works only if you are using a MySQL database!"
  bpreload:
    usage: /bpreload
    description: "to reload the config files"

permissions:
  backpacks.*:
    description: "all access (for admins)"
    default: op
    children:
      backpack.help: true
      backpacks.littleBackPack: true
      backpacks.normalBackPack: true
      backpacks.enderBackPack: true
      backpacks.workbenchBackPack: true
      backpacks.enchantingBackPack: true
      backpacks.furnaceBackPack: true
      backpacks.give: true
      backpacks.reload: true
      backpacks.open: true
  backpacks.help:
    description: "for /backpacks help"
    default: true
  backpacks.give:
    description: "to give anyone a backpack (the /bpgive command)"
    default: op
  backpacks.reload:
    description: "to use the /bpreload command"
    default: op
  backpacks.littleBackPack:
    description: "to use the little backpack"
    default: true
  backpacks.normalBackPack:
    description: "to use the normal backpack"
    default: true
  backpacks.enderBackPack:
    description: "to use the ender backpack"
    default: true
  backpacks.workbenchBackPack:
    description: "to use the workbench back pack"
    default: true
  backpacks.enchantingBackPack:
    description: "to use the enchanting backpack"
    default: true
  backpacks.furnaceBackPack:
    description: "to use the furnace backpack"
    default: true
  backpacks.open:
    description: "to use /bpopen"
    default: op