#
# BackPacks 2.0.0-ALPHA
# By michael1011
#

# Don"t touch this variable! It would destroy your config files!
configVersion: 0

# Setup you MySQL connection here
MySQL:
  host: "localhost"
  port: "3306"
  database: "bp"
  username: "bp"
  password: "psswrd"

# Delete the defaults and create your own backpacks here
# Find all materials here: http://bit.ly/21vbetj
BackPacks:
  enabled:
    1: "littleBackPack"
    2: "normalBackPack"
  # List all BackPacks here that should be enabled

  littleBackPack:
    name: "&bLittle &3BackPack"

    description:
      1: "&fThis is the &bLittle &3BackPack&f."
      2: "&8Right click to open it."

    # Must be divisible by 9
    slots: 9

    material: "COMPASS"

    crafting:
      1: "I+L+I"
      2: "L+C+L"
      3: "I+L+I"

      materials:
        I: "IRON_INGOT"
        L: "LEATHER"
        C: "COMPASS"

  normalBackPack:
    name: "&eNormal &6BackPack"

    description:
      1: "&fThis is the &eNormal &6BackPack&f."
      2: "&8Right click to open it."

    slots: 27

    material: "WATCH"

    crafting:
      1: "R+G+R"
      2: "G+W+G"
      3: "R+G+R"

      materials:
        R: "REDSTONE_BLOCK"
        G: "GOLD_BLOCK"
        W: "WATCH"