#
# BackPacks 2.3.0
# By michael1011
#

# Don't touch this variable! It would destroy your config files!
configVersion: 3

# Setup your MySQL connection here
MySQL:
  host: "localhost"
  port: "3306"
  database: "bp"
  username: "bp"
  password: "psswrd"

  # Only useful for NamelessMC (https://github.com/NamelessMC/Nameless)
  syncBackPacks: false


# If a player dies with a backpack in his inventory should the content of backpack get dropped too?
dropOnDeath: true

# Should players be able to store backpacks in backpacks?
BackPackInBackPack: false

# When you click on one of these items the BackPack won't open
# You can find the materials here: http://bit.ly/21vbetj
# The materials aren't case sensitive
# A '*' will add any material that matches the characters before to the list
doNotOpen:
  - WORKBENCH
  - FURNACE
  - BURNING_FURNACE
  - CHEST
  - TRAPPED_CHEST
  - ENDER_CHEST
  - ENCHANTMENT_TABLE
  - ANVIL
  - HOPPER
  - DISPENSER
  - SHULKER_BOX*

# the updater will search for updates here: http://bit.ly/2cXN1dD
# and it will only use versions with the type 'release'
Updater:
  enabled: true

  # in whole hours
  interval: 24

  # if this is true the plugin will download the latest version and reload the server after the download automatically
  # if it's false it will send every player with the permission 'backpacks.update' a message that a new version is available on join
  autoUpdate: false


# Delete the defaults and create your own backpacks here
# You can create backpacks with the /bpcreate command too
# Find all materials here: http://bit.ly/21vbetj

# Important: every description must be unique!
BackPacks:
  # List all BackPacks that should be enabled
  enabled:
    1: "littleBackPack"
    2: "normalBackPack"
    3: "enderBackPack"
    4: "craftingBackPack"
    5: "furnaceBackPack"

  littleBackPack:
    name: "&bLittle &3BackPack"
    type: "normal"

    # Important: every description must be unique!
    description:
      1: ""
      2: "&fThis is the &bLittle &3BackPack&f."
      3: "&8Right click to open it."

    # Must be divisible by 9
    slots: 9

    material: "COMPASS"

    crafting:
      1: "I+L+I"
      2: "L+C+L"
      3: "I+L+I"

      materials:
        I: "IRON_INGOT"
        L: "LEATHER"
        C: "COMPASS"

  normalBackPack:
    name: "&eNormal &6BackPack"
    type: "normal"

    description:
      1: ""
      2: "&fThis is the &eNormal &6BackPack&f."
      3: "&8Right click to open it."

    slots: 27

    material: "WATCH"

    crafting:
      1: "R+G+R"
      2: "G+W+G"
      3: "R+G+R"

      materials:
        R: "REDSTONE_BLOCK"
        G: "GOLD_BLOCK"
        W: "WATCH"

  enderBackPack:
    name: "&5Ender &dBackPack"
    type: "ender"

    description:
      1: ""
      2: "&fThis is the &5Ender &dBackPack&f."
      3: "&8Right click to open it."

    material: "ENDER_CHEST"

    crafting:
      1: "P+O+P"
      2: "O+W+O"
      3: "P+O+P"

      materials:
        P: "ENDER_PEARL"
        W: "ENDER_CHEST"
        O: "OBSIDIAN"

  craftingBackPack:
    name: "&7Crafting &8BackPack"
    type: "crafting"

    description:
      1: ""
      2: "&fThis is the &7Crafting &8BackPack&f."
      3: "&8Right click to open it."

    material: "WORKBENCH"

    crafting:
      1: "R+W+R"
      2: "W+W+W"
      3: "R+W+R"

      materials:
        R: "REDSTONE"
        W: "WORKBENCH"

  furnaceBackPack:
    name: "&cFurnace &4BackPack"
    type: "furnace"

    description:
      1: ""
      2: "&fThis is the &cFurnace &4BackPack&f."
      2: "&8Right click to open it."

    gui:
      enabled: true

    material: "FURNACE"

    crafting:
      1: "C+B+C"
      2: "B+F+B"
      3: "C+B+C"

      materials:
        C: "COAL"
        B: "COAL_BLOCK"
        F: "FURNACE"