#
# BackPacks 2.0.0-RC2
# By michael1011
#

# Don't touch this variable! It would destroy your config files!
configVersion: 0

# Setup your MySQL connection here
MySQL:
  host: "localhost"
  port: "3306"
  database: "bp"
  username: "bp"
  password: "psswrd"


# If a player dies with a backpack in his inventory should the content of backpack get dropped too?
dropOnDeath: true


# Delete the defaults and create your own backpacks here
# Find all materials here: http://bit.ly/21vbetj
BackPacks:
  # List all BackPacks that should be enabled
  enabled:
    1: "littleBackPack"
    2: "normalBackPack"
    3: "enderBackPack"
    4: "furnaceBackPack"

  littleBackPack:
    name: "&bLittle &3BackPack"
    type: "normal"

    description:
      1: "&fThis is the &bLittle &3BackPack&f."
      2: "&8Right click to open it."

    # Must be divisible by 9
    slots: 9

    material: "COMPASS"

    crafting:
      1: "I+L+I"
      2: "L+C+L"
      3: "I+L+I"

      materials:
        I: "IRON_INGOT"
        L: "LEATHER"
        C: "COMPASS"

  normalBackPack:
    name: "&eNormal &6BackPack"
    type: "normal"

    description:
      1: "&fThis is the &eNormal &6BackPack&f."
      2: "&8Right click to open it."

    slots: 27

    material: "WATCH"

    crafting:
      1: "R+G+R"
      2: "G+W+G"
      3: "R+G+R"

      materials:
        R: "REDSTONE_BLOCK"
        G: "GOLD_BLOCK"
        W: "WATCH"

  enderBackPack:
    name: "&5Ender &dBackPack"
    type: "ender"

    description:
      1: "&fThis is the &5Ender &dBackPack&f."
      2: "&8Right click to open it."

    material: "ENDER_CHEST"

    crafting:
      1: "P+O+P"
      2: "O+W+O"
      3: "P+O+P"

      materials:
        P: "ENDER_PEARL"
        W: "ENDER_CHEST"
        O: "OBSIDIAN"

  furnaceBackPack:
    name: "&cFurnace &4BackPack"
    type: "furnace"

    description:
      1: "&fThis is the &cFurnace &4BackPack&f."
      2: "&8Right click to open it."

    gui:
      enabled: true

    material: "FURNACE"

    crafting:
      1: "C+B+C"
      2: "B+F+B"
      3: "C+B+C"

      materials:
        C: "COAL"
        B: "COAL_BLOCK"
        F: "FURNACE"