name: BackPacks
author: michael1011
version: 2.2.0
description: A backpack plugin for Bukkit/Spigot 1.10 and 1.9
website: https://michael1011.at/projects/backpacks/

main: at.michael1011.backpacks.Main

commands:
  bpgive:
    aliases: [bpg]
    description: "give a backpack to a player"
    usage: /bpgive <backpack> <player>

  bpopen:
    aliases: [bpo]
    description: "see the backpack of a player"
    usage: /bpopen <backpack> <player>
    
  bpcreate:
    aliases: [bpc]
    description: "create new backpacks easily"
    usage: /bpc <name of the new backpack>

  bpreload:
    aliases: [bpr]
    description: "reload the configuration files"
    usage: /bpr

  bplist:
    aliases: [bpl]
    description: "list all backpacks"
    usage: /bpl


permissions:
  backpacks.*:
    description: all access
    children:
      backpacks.give: true
      backpacks.open: true
      backpacks.create: true
      backpacks.reload: true
      backpacks.update: true
      backpacks.list: true

  backpacks.give:
    description: to use /bpgive
    default: op
  backpacks.open:
    description: to use /bpopen
    default: op
  backpacks.create:
    description: to use /bpcreate
    default: op
  backpacks.reload:
    description: to use /bpreload
    default: op
  backpacks.update:
    description: to get a message when a new version is available
    default: op
  backpacks.list:
    description: to list all backpacks
    default: op
