name: BackPacks
author: michael1011
version: 1.0.0-ALPHA
description: A backpack plugin for Bukkit/Spigot 1.10 and 1.9

main: at.michael1011.backpacks.Main

commands:
  bpgive:
    aliases: [bpg]
    permission: backpacks.give
    description: "Give anyone a backpack"
    usage: /bpgive <backpack> <player>

permissions:
  backpacks.*:
    description: All access
    children:
      backpacks.give: true

  backpacks.give:
    description: To use /bpgive
    default: op