name: BackPacks
author: michael1011
version: 2.0.0-RC1
description: A backpack plugin for Bukkit/Spigot 1.10 and 1.9

main: at.michael1011.backpacks.Main

commands:
  bpgive:
    aliases: [bpg]
    description: "Give a backpack to everyone"
    usage: /bpgive <backpack> <player>

  bpopen:
    aliases: [bpo]
    dedescription: "See the backpacks of everyone"
    usage: /bpopen <backpack> <player>


permissions:
  backpacks.*:
    description: All access
    children:
      backpacks.give: true

  backpacks.give:
    description: To use /bpgive
    default: op
  backpacks.open:
    description: To use /bpopen
    default: op