name: BackPacks
author: michael1011
version: 2.1.0
description: A backpack plugin for Bukkit/Spigot 1.10 and 1.9

main: at.michael1011.backpacks.Main

commands:
  bpgive:
    aliases: [bpg]
    description: "give a backpack to a player"
    usage: /bpgive <backpack> <player>

  bpopen:
    aliases: [bpo]
    description: "see the backpacks of all players"
    usage: /bpopen <backpack> <player>


permissions:
  backpacks.*:
    description: all access
    children:
      backpacks.give: true
      backpacks.open: true

  backpacks.give:
    description: to use /bpgive
    default: op
  backpacks.open:
    description: to use /bpopen
    default: op